# Configuration: https://dependabot.com/docs/config-file/
# Docs: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "rack-throttle"
        versions: [">=0.7.1"]
      # FIXME: Bootstrap Bug
      # https://github.com/pglombardo/PasswordPusher/issues/1377
      - dependency-name: "bootstrap"
        versions: [">5.2.3"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50

  - package-ecosystem: "docker"
    directory: "/containers/docker"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"
    open-pull-requests-limit: 50
