# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  expire_pushes:
    class: ExpirePushesJob
    queue: recurring
    schedule: every 2 hours

  cleanup_pushes:
    class: CleanUpPushesJob
    queue: recurring
    schedule: every day at 5am

  purge_expired_pushes:
    class: PurgeExpiredPushesJob
    queue: recurring
    schedule: every day at 4am

  purge_unattached_blobs:
    class: PurgeUnattachedBlobsJob
    queue: recurring
    schedule: every 3 days

  cleanup_cache:
    class: CleanupCacheJob
    queue: recurring
    schedule: every day at 3am

development:
  expire_pushes:
    class: ExpirePushesJob
    queue: recurring
    schedule: every 4 hours

  cleanup_pushes:
    class: CleanUpPushesJob
    queue: recurring
    schedule: every 7 hours

  purge_expired_pushes:
    class: PurgeExpiredPushesJob
    queue: recurring
    schedule: every day at 4am

  purge_unattached_blobs:
    class: PurgeUnattachedBlobsJob
    queue: recurring
    schedule: every 3 days

  cleanup_cache:
    class: CleanupCacheJob
    queue: recurring
    schedule: every 6 hours
