services:
  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: 'pwpush_user'
      MYSQL_PASSWORD: 'pwpush_passwd'
      MYSQL_DATABASE: 'pwpush_db'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./mysql-data:/var/lib/mysql

  pwpush:
    image: docker.io/pglombardo/pwpush:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - db
    links:
     - db:mysql
    environment:
      DATABASE_URL: 'mysql2://pwpush_user:pwpush_passwd@db:3306/pwpush_db'
      #
      # Specify a domain in the TLS_DOMAIN environment variable to automatically provision a TLS (SSL) certificate for the application.
      # Uncomment the following line to set the TLS_DOMAIN environment variable.
      # TLS_DOMAIN: 'pwpush.example.com'
      #
      # You can set additional environment variables here, or in a .env file.  See:
      # https://docs.docker.com/compose/environment-variables/
      #
      # Password Pusher provides an example Docker environment file:
      # https://github.com/pglombardo/PasswordPusher/tree/master/containers/docker/pwpush-docker-env-file
      #
      # See also the Password Pusher Configuration documentation
      # https://docs.pwpush.com/docs/config-strategies/
      #
      # Uncomment the following lines to set environment variables and add your own.
      # PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT: "1"
      # PWP__PW__EXPIRE_AFTER_VIEWS_MIN: "1"
      # PWP__PW__RETRIEVAL_STEP_DEFAULT: "true"
      #
      # Uncomment the following lines to mount a volume.
      # volumes:
      #   # Example of a persistent volume for the storage directory (file uploads)
      #   - /path/to/directory:/opt/PasswordPusher/storage:rw
      #
      # Or you could override a single file in the container with a bind mount:
      # volumes:
      #   - type: bind
      #     source: /path/to/my/custom/settings.yml
      #     target: /opt/PasswordPusher/config/settings.yml
      #
      # To customise the application via configuration file, see settings.yml:
      # https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml
      #
      # Then you can use the above bind mount to overlay the file into the container on boot.